# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            JGG Codr
tagline:          Codr skills enhancements
url:              http://juliengarcia.github.io
paginate:         5
baseurl:          /
author:
  name:           Julien Garcia Gonzalez
  url:            https://twitter.com/_garcia_j_
  email:          garciagonzalez.julien@gmail.com
description:      <div id="about_tag" class='spring_about_tag' ></div> "Spring & Hibernate Codr with &hearts;"

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/juliengarcia
